name: dstu_schedule
description: "Мобильное приложение расписания ДГТУ с офлайн-кэшем и отслеживанием изменений"
publish_to: 'none'
version: 1.4.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.1
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  workmanager: ^0.10.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
